Repository re-quest-team/request, pull requests merged in 2022-06, with the labels that each got.

#56 Instagram develop
  collections/Media/Instagram/EditView.tsx
  collections/Media/Instagram/PlayView.tsx
  collections/Media/Instagram/index.tsx
  collections/Media/Instagram/store.tsx
  collections/index.ts
Labels: On current Sprint, Ready for review

#54 Printable QR Codes with link to game #30
  features/game/components/GamePanel.tsx
  features/game/components/QrCode/PdfTemplate.tsx
  features/game/components/QrCode/QrCodeConfig.ts
  lang/de.json
  lang/en.json
  package.json
  yarn.lock
Labels: On current Sprint, Ready for review, Sprint3

#59 Add YouTube Embed Module #45
  collections/Media/Youtube/EditView.tsx
  collections/Media/Youtube/PlayView.tsx
  collections/Media/Youtube/index.tsx
  collections/Media/Youtube/store.tsx
  collections/index.ts
  lang/de.json
  lang/en.json
Labels: On current Sprint, Ready for review, Sprint3

#61 Develop multiple choice
  collections/Quests/MultipleChoice/EditView.tsx
  collections/Quests/MultipleChoice/PlayView.tsx
  collections/Quests/MultipleChoice/index.ts
  collections/Quests/MultipleChoice/store.tsx
  collections/index.ts
  features/quest/components/AddQuestButton.tsx
  features/quest/components/PlayQuestButton.tsx
  lang/de.json
  lang/en.json
Labels: On current Sprint, Ready for review, Sprint3

#72 Develop show quest after solved merging into develop
  features/quest/components/QuestImagePlacer.tsx
  features/quest/components/QuestTypeModal.tsx
  features/room/components/RoomView.tsx
  lang/de.json
  lang/en.json
Labels: On current Sprint, Ready for review, Sprint4

#77 Develop image media
  collections/Media/Image/EditView.tsx
  collections/Media/Image/PlayView.tsx
  collections/Media/Image/index.tsx
  collections/Media/Image/store.tsx
  collections/index.ts
  lang/de.json
  lang/en.json
Labels: On current Sprint, Ready for review, Sprint4
